# Generated by Django 4.1.7 on 2023-03-25 04:27

from django.db import migrations, models
import django.db.models.deletion
import memorymap.models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=memorymap.models.Location.img_path)),
                ('address', models.CharField(blank=True, max_length=127, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('hold_date', models.DateTimeField()),
                ('lat', models.FloatField(verbose_name='')),
                ('lon', models.FloatField(verbose_name='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorymap.event')),
            ],
        ),
    ]
