# Generated by Django 4.1.7 on 2023-03-25 04:59

from django.db import migrations, models
import django.db.models.deletion
import memorymap.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=127)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=memorymap.models.Location.img_path)),
                ('address', models.CharField(blank=True, max_length=127, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('hold_date', models.DateTimeField()),
                ('lat', models.FloatField(verbose_name='')),
                ('lon', models.FloatField(verbose_name='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorymap.event')),
            ],
        ),
    ]
